# Simulado 3 - Rainhas Amigas com uma Intriga
# Python 3.7.1

# O nome de seu arquivo de entrada deve ser "arquivo_teste.txt"
# Ou podes simplesmente digitar "python rainhas_intriga.py < [nome_do_arquivo_teste].txt"
default:
	python karatsuba.py < arquivo_teste.txt